app = "market-tth"

kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  BOT_TOKEN = "7964268980:AAH5QFV0PY98hSiNw0v6rjYDutkWa1CN0hM"
  # Другие переменные окружения при необходимости

[processes]
  web    = "uvicorn app:app --host 0.0.0.0 --port 8080"
  worker = "python main.py"

[[services]]
  # Разрешаем этому сервису обрабатывать только процесс web
  processes    = ["web"]
  internal_port = 8080
  protocol      = "tcp"

  [services.concurrency]
    type       = "connections"
    soft_limit = 20
    hard_limit = 25

  [[services.ports]]
    handlers = ["http"]
    port     = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port     = 443
